### ISSUE TITLE
Proto target loses dependence information

### ISSUE THREAD

**Issue by VankiCu** [TOMO-CAT/xmake#30]
protobuf.cpp rule only have one `batchcmds` 's depfiles:

![image](https://github.com/user-attachments/assets/19b4c4f8-719b-4613-ae82-0a73c70f462a)

if I use the protobuf.cpp rule's `extra_flags`:

```lua
target("foo.proto", function()
    set_kind("object")
    add_files("foo/proto/*.proto", { public = true, proto_rootdir = "foo"})
    add_rules("protobuf.cpp")
    add_packages("protobuf-cpp")
    set_policy('build.fence', true)
end)

target("test.proto", function()
    set_kind("object")

    add_files("proto/*.proto", { proto_public = true, proto_rootdir = ".", extra_flags = { "-Ifoo" } })

    add_rules("protobuf.cpp")
    add_packages("protobuf-cpp", { public = true })

    set_policy('build.fence', true)
    add_deps("foo.proto")
    add_includedirs("build/.gens/foo.proto/linux/x86_64/release/rules/protobuf/foo", {public = true})
end)
``` 

in this example, If I modify foo.proto, it will not trigger a recompilation of test.proto

**Comment by VankiCu** [comment]
foo/proto/header.proto:

```proto
syntax = "proto3";

package github.tomocat.proto;

message End2EndSource {
  string module_name = 1;
  uint32 sequence_num = 2;
  double transit_time_ms = 3;
}
```

proto/test.proto:

```proto
syntax = "proto3";

package github.tomocat.proto;

import "proto/header.proto";

message Version {
  int32 major_version = 1;
  int32 minor_version = 2;
  int32 patch_version = 3;
  End2EndSource e2e_source = 4;
}
```

main.cc:

```c++
#include <iostream>

#include "proto/test.pb.h"

int main() {
    std::cout << "test protobuf.cpp rule" << std::endl;
    ::github::tomocat::proto::Version version;
    version.set_major_version(1);
    version.set_minor_version(2);
    version.set_patch_version(3);
    version.mutable_e2e_source()->set_module_name("cat");
    return 0;
}
```

I can compile successfully:
![image](https://github.com/user-attachments/assets/2a826bff-90b1-4bff-86f5-df5c5119911e)

then I change the content of header.proto:
![image](https://github.com/user-attachments/assets/294be8ae-e0f2-4537-836c-f007206d80e5)

![image](https://github.com/user-attachments/assets/fa7542ea-8f61-4843-9dae-ba69d4e13df7)

I tried incremental compilation using `xmake -b`:
![image](https://github.com/user-attachments/assets/3e3e8ff7-60e1-4f9b-91e1-603b5b0dd1db)

It's weird that test.proto don't compile.

I have to run `xmake -br` to compile completely!

**Comment by VankiCu** [comment]
> I have to run `xmake -br` to compile completely!

![image](https://github.com/user-attachments/assets/aaaa7901-d0b1-448a-982e-c137f87bf9a5)

**Comment by TOMO-CAT** [comment]
There is a bit of trouble, I will try to handle it as follows

> https://groups.google.com/g/protobuf/c/PKQde2JIDSo
